import 'ComplaintListModel.dart';

class ComplaintData {
  static List<ComplaintListModels> getComplains = [

    ComplaintListModels(
      complaintId: 1,
      complaintDate: '2023-07-28',
      priority: 'High',
      assignment: 'John Doe',
      workStart: '09:00 AM',
      workEnd: '05:00 PM',
      equipment: 'Equipment A',
      make: 'ABC Company',
      model: 'Model X',
      serialNo: '12345',
      equipmentId: 1001,
      status: 'Pending',
    ),

    ComplaintListModels(
      complaintId: 2,
      complaintDate: '2023-07-29',
      priority: 'Medium',
      assignment: 'Jane Smith',
      workStart: '10:00 AM',
      workEnd: '06:00 PM',
      equipment: 'Equipment B',
      make: 'XYZ Corporation',
      model: 'Model Y',
      serialNo: '67890',
      equipmentId: 1002,
      status: 'In Progress',
    ),

    ComplaintListModels(
      complaintId: 3,
      complaintDate: '2023-07-30',
      priority: 'Low',
      assignment: 'Michael Johnson',
      workStart: '08:30 AM',
      workEnd: '04:30 PM',
      equipment: 'Equipment C',
      make: 'DEF Enterprises',
      model: 'Model Z',
      serialNo: '54321',
      equipmentId: 1003,
      status: 'Completed',
    ),

    ComplaintListModels(
      complaintId: 4,
      complaintDate: '2023-07-31',
      priority: 'High',
      assignment: 'Robert Brown',
      workStart: '09:30 AM',
      workEnd: '05:30 PM',
      equipment: 'Equipment D',
      make: 'GHI Industries',
      model: 'Model W',
      serialNo: '98765',
      equipmentId: 1004,
      status: 'Pending',
    ),

    ComplaintListModels(
      complaintId: 5,
      complaintDate: '2023-08-01',
      priority: 'Medium',
      assignment: 'Emily Davis',
      workStart: '10:30 AM',
      workEnd: '06:30 PM',
      equipment: 'Equipment E',
      make: 'JKL Corp',
      model: 'Model V',
      serialNo: '13579',
      equipmentId: 1005,
      status: 'Pending',
    ),

    ComplaintListModels(
      complaintId: 6,
      complaintDate: '2023-08-02',
      priority: 'High',
      assignment: 'William Wilson',
      workStart: '09:00 AM',
      workEnd: '05:00 PM',
      equipment: 'Equipment F',
      make: 'MNO Industries',
      model: 'Model U',
      serialNo: '24680',
      equipmentId: 1006,
      status: 'In Progress',
    ),

    ComplaintListModels(
      complaintId: 7,
      complaintDate: '2023-08-03',
      priority: 'Medium',
      assignment: 'Sophia Martinez',
      workStart: '10:00 AM',
      workEnd: '06:00 PM',
      equipment: 'Equipment G',
      make: 'PQR Tech',
      model: 'Model T',
      serialNo: '97531',
      equipmentId: 1007,
      status: 'Completed',
    ),

    ComplaintListModels(
      complaintId: 8,
      complaintDate: '2023-08-04',
      priority: 'Low',
      assignment: 'Liam Johnson',
      workStart: '08:30 AM',
      workEnd: '04:30 PM',
      equipment: 'Equipment H',
      make: 'STU Innovations',
      model: 'Model S',
      serialNo: '86420',
      equipmentId: 1008,
      status: 'Pending',
    ),

    ComplaintListModels(
      complaintId: 9,
      complaintDate: '2023-08-05',
      priority: 'High',
      assignment: 'Olivia Davis',
      workStart: '09:30 AM',
      workEnd: '05:30 PM',
      equipment: 'Equipment I',
      make: 'VWX Systems',
      model: 'Model R',
      serialNo: '75319',
      equipmentId: 1009,
      status: 'In Progress',
    ),

    ComplaintListModels(
      complaintId: 10,
      complaintDate: '2023-08-06',
      priority: 'Medium',
      assignment: 'Noah Smith',
      workStart: '10:30 AM',
      workEnd: '06:30 PM',
      equipment: 'Equipment J',
      make: 'YZ Enterprises',
      model: 'Model Q',
      serialNo: '64208',
      equipmentId: 1010,
      status: 'Pending',
    ),
  ];
}